### ISSUE TITLE
Populations missing for certain countries

### ISSUE THREAD

**Issue by greydwarf** [M-Media-Group/Covid-19-API#1]
There are some populations missing for several countries:
Bahamas, The
Cabo Verde
Congo (Brazzaville)
Congo (Kinshasa)
Cote d'Ivoire
Czechia
Eswatini
Fiji
Gambia, The
Holy See
Korea, South
Kosovo
Montenegro
Russia
Serbia
Sri Lanka
Taiwan*
US

This is likely caused by the country names from the COVID-19 data not matching the names in the population data source.

**Comment by mwargan** [comment]
@greydwarf thanks for reporting! 

Yes this is exactly the issue, there needs to be a way to standardise/lookup country names from a range of input sources. I'm looking into it - any ideas on your end?

**Comment by mwargan** [comment]
[Forked the original population source](https://github.com/M-Media-Group/country-json) and updated country names to match - fixed:

- Bahamas, The (didn't seem to be missing population data when I checked, COVID data may have been updated)
- Fiji
- Gambia, The (didn't seem to be missing population data when I checked, COVID data may have been updated)
- Holy See
- Korea, South
- Russia
- Sri Lanka

**Comment by mwargan** [comment]
Closing for now, feel free to open for new countries on the population source repo.
