### ISSUE TITLE
Inconsistent license information?

### ISSUE THREAD

**Issue by hplewis** [M-Media-Group/Covid-19-API#13]
In your project, you have a GPLv3 `LICENSE` file, but in the README, you state that it is licensed under AGPLv3. In addition, you also provide other stipulations such as restrictions for commercial use, while the license allows commercial use.

This results in a lot of ambiguity with how the API should be used or modified.

**Comment by mwargan** [comment]
@hplewis that's a very good point! What use case are you envisioning?

Generally I wanted to ensure that people don't make money by creating their own API that just calls this one in the background, and charging for theirs (and similar practices).

I'll have a think of what licence is actually applicable - though let me know if you have suggestions!

**Comment by hplewis** [comment]
I actually am not planning on using this myself, just saw your project and thought it was cool!

If you're worried about people ripping off your work and making money on it, I think AGPLv3 provides the best restrictions. It would make it so that anyone who hosts their own version of this API make the code available, including their own modifications.

However, I don't think it prevents commercial use outright. Might need someone more familiar with law to help with that one. 

Personally, I think AGPLv3 is probably the best bet for what you're aiming for.

**Comment by hplewis** [comment]
You might be able to come up with some terms of use for your specific hosting of the API, which disallows commercial use. I'm not as familiar with that, though.

**Comment by mwargan** [comment]
Updated to AGPLv3 in https://github.com/M-Media-Group/Covid-19-API/commit/0f4803eb6fe981390bbe96c36a80fb441bd93391
