### ISSUE TITLE
CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource

### ISSUE THREAD

**Issue by rajib317** [M-Media-Group/Covid-19-API#15]
Tested from localhost and also from SSL enabled server.

**Comment by mwargan** [comment]
Which resource are you requesting?

**Comment by mwargan** [comment]
Thanks, now resolved: https://github.com/M-Media-Group/Covid-19-API/commit/c70fd364343827e96a3011548eb74d20462edb50

**Comment by rajib317** [comment]
Hello all,

I'm trying to access this resource

const request = fetch('https://covid-api.mmediagroup.fr/v1?country=India');

I'm still getting 403 error

**Comment by mwargan** [comment]
@rajib317 please open new issues when you face new issues :)! Your request seems malformed - make sure you are either calling the full endpoints as needed - in your example you are missing either "cases" or "history" in your URL.
