### ISSUE TITLE
US Recovered showing 0

### ISSUE THREAD

**Issue by CrisesKhaos** [M-Media-Group/Covid-19-API#17]
The recovered cases in [US](https://covid-api.mmediagroup.fr/v1/cases?country=US) is showing 0,
Furthermore ,the confirmed cases in [Chile](https://covid-api.mmediagroup.fr/v1/cases?country=Chile) are less than Recovered?

**Comment by mwargan** [comment]
Hey @CrisesKhaos.

As mentioned in the README (although maybe not too clearly), recovered data was depreciated by our data provider, see issue:  https://github.com/CSSEGISandData/COVID-19/issues/3464 (warning, some coarse words there)...

Regarding Chile, see issue: https://github.com/CSSEGISandData/COVID-19/issues/4033 - this will hopefully be resolved soon with the data provider.

**Comment by CrisesKhaos** [comment]
Okey,  thanks for the clarification @mwargan !
