### ISSUE TITLE
Number of deaths wrong for current day

### ISSUE THREAD

**Issue by gdeggau** [M-Media-Group/Covid-19-API#2]
First of all, it is a good job, congratulations. When request a history data from a country, the value of current day is the same from previously day.

For example: https://covid-api.mmediagroup.fr/v1/history?country=Brazil&status=Deaths
![image](https://user-images.githubusercontent.com/37387111/77381956-dcae0680-6d5d-11ea-9c6a-40a73f2635ab.png)

Look, the days 22 and 23 have the same deaths number (25), but in field "deaths" we can the live data, which is showing 34.

Is it possible to change the value of current day in history dates to get the current data?

**Comment by mwargan** [comment]
Thanks for raising the issue @gdeggau :)!

The discrepancy comes from the fact that they come from two different data sources. I was looking to remove the current deaths/confirmed/recovered from the /history endpoint as it's already available on the /cases endpoint.

Thoughts on that? Would it affect your already deployed projects?

**Comment by gdeggau** [comment]
> Thanks for raising the issue @gdeggau :)!
> 
> The discrepancy comes from the fact that they come from two different data sources. I was looking to remove the current deaths/confirmed/recovered from the /history endpoint as it's already available on the /cases endpoint.
> 
> Thoughts on that? Would it affect your already deployed projects?

Ok, i got it.

I'm actually looking for a easiest dataset/API to build a dashboard on PowerBI, if you change will not affect my project, i'm just using the history datas.

**Comment by mwargan** [comment]
Great! I'll be closing this issue then and gradually implementing this change.

Feel free to open a pull request or new issue to add your project to the Readme :)
