### ISSUE TITLE
Issue

### ISSUE THREAD

**Issue by VaidikRungta** [M-Media-Group/Covid-19-API#23]
Does it only show stats of specific countries or it shows global statics well?

**Comment by mwargan** [comment]
@VaidikRungta global data is shown under "Global". As an example, see the very bottom of this response: https://covid-api.mmediagroup.fr/v1/cases.

**Comment by VaidikRungta** [comment]
> @VaidikRungta global data is shown under "Global". As an example, see the very bottom of this response: https://covid-api.mmediagroup.fr/v1/cases.

okay thanks @mwargan
