### ISSUE TITLE
could not access the covid api

### ISSUE THREAD

**Issue by mithunprithvi** [M-Media-Group/Covid-19-API#32]
could not access the covid api for the cases where the data set is missing

**Comment by mwargan** [comment]
Looks like the original data source is now access restricted. https://opendata.arcgis.com/datasets/bbb2e4f589ba40d692fab712ae37b9ac_1.csv

We may need to switch data sources. I'm open to suggestions :)

**Comment by mwargan** [comment]
Switched to JHE datasource

**Comment by mithunprithvi** [comment]
Thank you for your email. That helps a lot
