### ISSUE TITLE
Cases Endpoint not returning expected Json Load

### ISSUE THREAD

**Issue by xoxoedg** [M-Media-Group/Covid-19-API#33]
Hi when i send a request to the cases endpoint. I get the following Json back
https://covid-api.mmediagroup.fr/v1/cases
{"Global": {"All": {"population": 7444509223, "confirmed": 0, "recovered": 0, "deaths": 0}}}

When i use query Parameters i get the same result.
https://covid-api.mmediagroup.fr/v1/cases?country=France

{"Global": {"All": {"population": 7444509223, "confirmed": 0, "recovered": 0, "deaths": 0}}}

Vaccines and History Endpoints are working

**Comment by mwargan** [comment]
Hmm, I'm not seeing this issue - can you confirm? https://covid-api.mmediagroup.fr/v1/cases

**Comment by xoxoedg** [comment]
Hi 
thank you for the quick reply. I tested it now with different countries and it works. 
Thank your very much!

**Comment by xoxoedg** [comment]
Well
now
https://covid-api.mmediagroup.fr/v1/cases?country=germany
this endpoint returns the data for all cases
![image](https://user-images.githubusercontent.com/84626740/146059130-451f0940-35ab-4e65-8e4d-2dac95e123f8.png)

**Comment by mwargan** [comment]
It's case sensitive - try https://covid-api.mmediagroup.fr/v1/cases?country=Germany

**Comment by RhysMalyon** [comment]
I'm running into the same issue even with the above link. Also getting a 500 error here: https://mmediagroup.fr/covid-19

**Comment by mwargan** [comment]
Hmm, must've been a hiccup, doesn't seem to be happening now.

**Comment by mwargan** [comment]
Closing this issue for now, feel free to create a new one should you run into any more problems.

**Comment by akshay-panchakshari** [comment]
> Closing this issue for now, feel free to create a new one should you run into any more problems.
Facing similar issue for vaccines api created #40
