### ISSUE TITLE
Vaccines data regarding Germany

### ISSUE THREAD

**Issue by xoxoedg** [M-Media-Group/Covid-19-API#34]
Hi

the response to the following endpoint : https://covid-api.mmediagroup.fr/v1/vaccines?country=Germany

return the expected JSON, but the fields "people_vaccinated" and "people_partially_vaccinated" always shows 0.
![image](https://user-images.githubusercontent.com/84626740/146647911-032be0a8-12f0-4ae5-8441-430aa2a91e9e.png)

Furthermore can you specify what the field "administered" means in the vaccines contect?

**Comment by xoxoedg** [comment]
Were you able to find smth regarding to that topic

**Comment by mwargan** [comment]
Hey @xoxoedg - my apologies, the holidays are really taking up my time this year. 

Administered means doses given (e.g. if you're fully vaccinated with something like Moderna, you will be administered 2 doses, or even 3+ if you also get a booster). In regards to the other numbers being 0 - I'll have a look later next week, but in the meantime, if you could check our data source and see if that data is even available, that would help tremendously!

**Comment by xoxoedg** [comment]
Hey Merry Christmas! 
Sure, I`ll check the datasource. Thanks for the answer!
