### ISSUE TITLE
{'message': 'Missing Authentication Token'}

### ISSUE THREAD

**Issue by giosroom99** [M-Media-Group/Covid-19-API#38]
Hi,
I would like to use this API but I can not get a response because of the following {'message': 'Missing Authentication Token'}
How do I get an Authentication Token or Sign up for one ?

**Comment by mwargan** [comment]
No token is required for this API. Just call it directly https://covid-api.mmediagroup.fr/v1/cases.

**Comment by Moodkiller20** [comment]
@mwargan  I tried using the link you provided and I am still getting {'message': 'Missing Authentication Token'} as a response.
