### ISSUE TITLE
Testing data

### ISSUE THREAD

**Issue by leandroparedes** [M-Media-Group/Covid-19-API#5]
Will testing data be available as history data?

Something like /history?status=testing

**Comment by mwargan** [comment]
Hey @leandroparedes! I took a look again at the original dataset source https://github.com/CSSEGISandData/COVID-19 but it looks like they don't provide the count of tests yet.

I currently don't know of any datasource that has reliable testing metrics for the whole world, though I agree it is important data.

**Comment by mwargan** [comment]
Closing due to lack of data source.
