### ISSUE TITLE
ISO 3166-1 Country codes

### ISSUE THREAD

**Issue by leandroparedes** [M-Media-Group/Covid-19-API#6]
Consider using ISO 3166-1 alpha-2 or alpha-3 country codes for accessing the data in a more standardized way.

E.g.
**/cases?country=FR** for obtain France cases data.

**Comment by mwargan** [comment]
@leandroparedes ISO abbreviations and numbers are now returned in the response object and I'm looking to make filtering based on additional parameters, such as /cases?ab=FR.

**Comment by mwargan** [comment]
@leandroparedes implemented - call with query parameter "ab": **/cases?ab=FR**
