### ISSUE TITLE
Add my Go program github to your README :)

### ISSUE THREAD

**Issue by ryanm404** [M-Media-Group/Covid-19-API#7]
Hello,
I talked with you on Reddit a few days ago regarding creating a Golang program that I was using for a personal project and you wanted me to put this here when I began work on it, so now I got it up on github finally! haha. It's still a work in progress , but it does work and it's pretty neat :) im u/lemonizer96 btw. here's my github link https://github.com/Fr0sty404/GoCoronaVirusAPIParser 
I also added a special thanks in my README to thank you and I made a link to your public API :)
Thank you for this !

**Comment by mwargan** [comment]
Done :)
